import type { ModelResponse, ProviderConfig, ProviderStatus, ToolCall } from './contracts.js';
import { decryptSecret, encryptSecret, maskSecret, StateStore } from '../storage/state.js';

export interface ChatMessage { role: 'system' | 'user' | 'assistant' | 'tool'; content: string | Array<Record<string, unknown>> | null; tool_call_id?: string; tool_calls?: unknown[]; }
export interface ProviderRequest { messages: ChatMessage[]; tools?: unknown[]; model?: string; visionImage?: string; }

const envProviders: ProviderConfig[] = [
  { id: 'openai', label: 'OpenAI-compatible / OpenAI', baseUrl: process.env.TARS_OPENAI_BASE_URL || 'https://api.openai.com/v1', apiKey: process.env.TARS_OPENAI_API_KEY || process.env.OPENAI_API_KEY, model: process.env.TARS_OPENAI_MODEL || 'gpt-5-mini', visionModel: process.env.TARS_OPENAI_VISION_MODEL || 'gpt-5', enabled: true },
  { id: 'anthropic', label: 'Anthropic-compatible', baseUrl: process.env.TARS_ANTHROPIC_BASE_URL || 'https://api.anthropic.com/v1', apiKey: process.env.TARS_ANTHROPIC_API_KEY, model: process.env.TARS_ANTHROPIC_MODEL || 'claude-sonnet-4-6', visionModel: process.env.TARS_ANTHROPIC_VISION_MODEL || 'claude-sonnet-4-6', enabled: true },
  { id: 'google', label: 'Google-compatible', baseUrl: process.env.TARS_GOOGLE_BASE_URL || 'https://generativelanguage.googleapis.com/v1beta/openai', apiKey: process.env.TARS_GOOGLE_API_KEY, model: process.env.TARS_GOOGLE_MODEL || 'gemini-3-flash-preview', visionModel: process.env.TARS_GOOGLE_VISION_MODEL || 'gemini-3-flash-preview', enabled: true },
];

export class ProviderManager {
  private readonly store: StateStore;
  private lastErrors = new Map<string, string>();
  private lastLatency = new Map<string, number>();
  constructor(store: StateStore) { this.store = store; }
  private allConfigs(): ProviderConfig[] { const stored = this.store.getProviders(); return envProviders.map((base) => { const saved = stored.find((p) => p.id === base.id); return saved ? { ...base, ...saved } : base; }).concat(stored.filter((p) => !envProviders.some((e) => e.id === p.id))); }
  private resolveKeys(config: ProviderConfig) { return (config.apiKeys?.length ? config.apiKeys : config.apiKey ? [config.apiKey] : []).map((value) => decryptSecret(value) ?? value).filter(Boolean); }
  statuses(): ProviderStatus[] { return this.allConfigs().map((config) => { const keys = this.resolveKeys(config); return { id: config.id, label: config.label, baseUrl: config.baseUrl, model: config.model, visionModel: config.visionModel, enabled: config.enabled, hasKey: keys.length > 0, maskedKey: maskSecret(keys[0]), lastError: this.lastErrors.get(config.id), lastLatencyMs: this.lastLatency.get(config.id) }; }); }
  saveProvider(input: Omit<ProviderConfig, 'apiKey' | 'apiKeys'> & { apiKey?: string }) { const existing = this.allConfigs().find((p) => p.id === input.id); const existingEncrypted = existing?.apiKeys?.length ? existing.apiKeys : existing?.apiKey ? [existing.apiKey] : []; const keys = input.apiKey?.trim() ? [...existingEncrypted, encryptSecret(input.apiKey.trim())] : existingEncrypted; this.store.upsertProvider({ ...existing, ...input, apiKey: keys[0], apiKeys: keys }); return this.statuses().find((p) => p.id === input.id); }
  removeProvider(id: string) { this.store.removeProvider(id); }
  async testProvider(id: string) { const config = this.allConfigs().find((p) => p.id === id); if (!config) throw new Error(`Provider ${id} is not configured.`); const result = await this.complete(config, { messages: [{ role: 'user', content: 'Reply with exactly: TARS_PROVIDER_OK' }], model: config.model }); return { ok: result.content.includes('TARS_PROVIDER_OK') || Boolean(result.content), providerId: id, latencyMs: result.latencyMs }; }
  async completeWithFallback(request: ProviderRequest, primaryId: string, fallbackId?: string): Promise<ModelResponse> { const ordered = [primaryId, fallbackId].filter((id, index, values): id is string => Boolean(id) && values.indexOf(id) === index); let lastError: unknown; for (const id of ordered) { const config = this.allConfigs().find((p) => p.id === id); if (!config || !config.enabled || !this.resolveKeys(config).length) continue; try { return await this.complete(config, request); } catch (error) { lastError = error; this.lastErrors.set(id, error instanceof Error ? error.message : String(error)); } } throw new Error(lastError instanceof Error ? lastError.message : 'No configured AI provider is available. Configure a provider API key and retry.'); }
  private async complete(config: ProviderConfig, request: ProviderRequest): Promise<ModelResponse> { let lastError: unknown; for (const apiKey of this.resolveKeys(config)) { try { return await this.completeWithKey(config, apiKey, request); } catch (error) { lastError = error; } } throw new Error(lastError instanceof Error ? lastError.message : `${config.label} API request failed.`); }
  private async completeWithKey(config: ProviderConfig, apiKey: string, request: ProviderRequest): Promise<ModelResponse> {
    const model = request.model || (request.visionImage ? config.visionModel : undefined) || config.model; const last = request.messages[request.messages.length - 1]; const content = request.visionImage ? [{ type: 'text', text: typeof last?.content === 'string' ? last.content : 'Inspect the current screen.' }, { type: 'image_url', image_url: { url: request.visionImage, detail: 'auto' } }] : last?.content; const messages = request.visionImage ? [...request.messages.slice(0, -1), { role: 'user' as const, content }] : request.messages;
    const body: Record<string, unknown> = { model, messages, tools: request.tools, tool_choice: request.tools?.length ? 'auto' : undefined, temperature: this.store.getSettings().temperature, max_tokens: this.store.getSettings().maxTokens }; if (model.startsWith('gpt-5')) { delete body.temperature; delete body.max_tokens; body.max_completion_tokens = this.store.getSettings().maxTokens; body.reasoning = { effort: 'low' }; }
    const started = Date.now(); let lastError: Error | undefined;
    for (let attempt = 0; attempt < 3; attempt += 1) { const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), this.store.getSettings().toolTimeoutMs + 30000); try { const response = await fetch(`${config.baseUrl.replace(/\/$/, '')}/chat/completions`, { method: 'POST', headers: { Authorization: `Bearer ${apiKey}`, 'Content-Type': 'application/json' }, body: JSON.stringify(body), signal: controller.signal }); const text = await response.text(); if (!response.ok) { const detail = safeProviderError(text, response.status); if (response.status === 401 || response.status === 403) throw new Error(`${config.label} authentication failed. Check the API key.`); if (response.status === 429 || response.status >= 500) { lastError = new Error(detail); await backoff(attempt, response.headers.get('retry-after')); continue; } throw new Error(detail); } const data = JSON.parse(text); const message = data.choices?.[0]?.message; if (!message) throw new Error(`${config.label} returned no model message.`); const latencyMs = Date.now() - started; this.lastLatency.set(config.id, latencyMs); this.lastErrors.delete(config.id); const toolCalls: ToolCall[] = (message.tool_calls ?? []).flatMap((call: any) => { try { return [{ id: call.id, name: call.function.name, arguments: JSON.parse(call.function.arguments || '{}') }]; } catch { return []; } }); return { content: typeof message.content === 'string' ? message.content : '', toolCalls, usage: data.usage ? { promptTokens: data.usage.prompt_tokens, completionTokens: data.usage.completion_tokens, totalTokens: data.usage.total_tokens } : undefined, providerId: config.id, model, latencyMs }; } catch (error) { if ((error as Error).name === 'AbortError') lastError = new Error(`${config.label} request timed out.`); else lastError = error instanceof Error ? error : new Error(String(error)); if (attempt < 2 && isRetryable(lastError)) { await backoff(attempt); continue; } break; } finally { clearTimeout(timer); } }
    throw lastError || new Error(`${config.label} request failed.`);
  }
}
function isRetryable(error: Error) { return /timeout|timed out|network|fetch|5\d\d|rate|429/i.test(error.message); }
async function backoff(attempt: number, retryAfter?: string | null) { const delay = retryAfter && /^\d+$/.test(retryAfter) ? Math.min(Number(retryAfter) * 1000, 10000) : 500 * (2 ** attempt); await new Promise((resolve) => setTimeout(resolve, delay)); }
function safeProviderError(raw: string, status: number) { try { const body = JSON.parse(raw); return body.error?.message || body.message || `Provider request failed (${status}).`; } catch { return `Provider request failed (${status}).`; } }
